### PR TITLE
Fix issue with simple-object-localization not showing on smaller viewports

### PR DESCRIPTION
**Pull request by kieran-osgood**
Due to the use of the vh on the image, at smaller width viewports the canvas doesn't draw over the image, changing `height:80vh` to `height: 100%` fixes the issue and retains previous functionality

# Current behaviour
## margin: 8 with **wide** viewport (notice whitespace to right of image)

image

## margin: 8 with **small** viewport (with **no** whitespace to right of image)
image

# New Behaviour
Even at small viewports the image is resized to the viewports width and therefore the bug isn't present
image

### CODE REVIEW

**Comment by kieran-osgood** [comment]
Perhaps adding a comment would also be useful, so people won't be distracted by the styles not matching whats in the text?

```
      <div style="position: relative;">
        <!-- NOTE: The styles are slightly different to fix rendering issues at small viewport widths  -->
        <img id="pet" src="/dog1.jpg" style="width: 100%" />
        <canvas id="detection" style="position: absolute; left: 0; "></canvas>
      </div>
```

**Comment by GantMan** [comment]
Good call!  Can you add that comment, and I'll merge?

**Comment by kieran-osgood** [comment]
@GantMan Done

**Comment by kieran-osgood** [comment]
Just got to chapter 6 and noticed the same things, so I'll update there too and update this PR

**Comment by GantMan** [comment]
thanks so much!

**Pull request merged**
